### ISSUE TITLE
Interactive Orbit Diagram : hbox! not defined

### ISSUE THREAD

**Issue by loiseaujc** [JuliaDynamics/InteractiveDynamics.jl#125]
Hi,

First, thx for this amazing package! I have started to use quite a bit for my nonlinear dynamics class. I recently installed Julia and all the packages of my new laptop and I'm running into a small problem whenever using `interactive_orbitdiagram`. Here is a minimal example:

```
# --> Sets up the parameters.
i = p_index = 1
ds, r_min, r_max, parname = Systems.logistic(), 1, 4, "μ"
title = "Orbit diagram"

# --> Plot the orbit diagram
interactive_orbitdiagram(ds, p_index, r_min, r_max, i ; parname=parname, title=title)
```

Whenever I run it, I get the following error:

```
ERROR: UndefVarError: hbox! not defined
Stacktrace:
 [1] add_controls!(controllayout::GridLayout, scene::Scene, D::Int64, parname::String, i0::Int64)
   @ InteractiveChaos ~/.julia/packages/InteractiveChaos/JO3KW/src/chaos/orbitdiagram.jl:311
 [2] interactive_orbitdiagram(ds::DiscreteDynamicalSystem{false, Float64, 1, typeof(DynamicalSystemsBase.Systems.logistic_rule), Vector{Float64}, typeof(DynamicalSystemsBase.Systems.logistic_jacob), Float64, false}, p_index::Int64, p_min::Int64, p_max::Int64, i0::Int64; u0::Float64, parname::String, title::String)
   @ InteractiveChaos ~/.julia/packages/InteractiveChaos/JO3KW/src/chaos/orbitdiagram.jl:64
 [3] top-level scope
   @ REPL[5]:1
```

The `Makie` window opens up correctly but the buttons are all messed up and nothing is plotted.
For info, I am using `Julia 1.8.4` along with
- `DynamicalSystems v2.3.2`
- `GLMakie v0.1.30`
- `InteractiveChaos v0.12.3`

I'm not sure what the problem is. It seems to me that, whenever I install `InteractiveChaos`, `GLMakie` is downdated to 0.1.30 even though it was initially v0.8 or something. Note however that I have no problem when running `interactive_cobweb` for instance.

**Comment by Datseris** [comment]
`GLMakie v0.1.30` is so old. This seems to be unrelated with our package thankfully. You need to find out why you can't install GLMakie 0.8. InteractiveDynamics is also on version 0.21...

Oh yeah. You are using the previous name of the package InteractiveChaos. Use InteractiveDynamcis instead.
