### ISSUE TITLE
interactive_evolution() seems broken in v 0.22.0

### ISSUE THREAD

**Issue by adhalanay** [JuliaDynamics/InteractiveDynamics.jl#131]
In the last version of the package, when trying to run the Lorenz example from documentation I get the error:
 

> interactive_evolution(::DynamicalSystem, ::Any; transform, idxs, tsidxs, colors, tail, lims, Δt, plotkwargs, m, total_span, linekwargs, ps, pnames, add_controls, steps_per_update, figure, axis, fade) at C:\Users\halan\.julia\packages\InteractiveDynamics\Q6bq5\src\chaos\trajanim.jl:108 got unsupported keyword argument "diffeq"

After removing the diffeq keyword I get another error:

> interactive_evolution(::DynamicalSystem, ::Any; transform, idxs, tsidxs, colors, tail, lims, Δt, plotkwargs, m, total_span, linekwargs, ps, pnames, add_controls, steps_per_update, figure, axis, fade) at C:\Users\halan\.julia\packages\InteractiveDynamics\Q6bq5\src\chaos\trajanim.jl:108 got unsupported keyword argument "diffeq"

Julia version : 1.8.5
OS version: Windows 11

**Comment by Datseris** [comment]
You're too fast!!!! I'm releasing the (breaking) DynamicalSystems.jl v3.0 as soon as possible! `diffeq` doesn't exist anymore! You give it directly to `CoupledODEs`, see here: https://juliadynamics.github.io/DynamicalSystemsBase.jl/dev/
