### ISSUE TITLE
Extend `brainscan_poincaresos` to multiple datasets

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/InteractiveDynamics.jl#27]
Would be nice to extend this function to accept multiple input datasets, all of  which are plotted at the same time but with different color, and the poincare section of all of which is also plotted with different colors (but all from the same plane).

This is easy to do.

**Comment by KalelR** [comment]
Hi, I think this is already implemented, right? cf. https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/master/src/chaos/brainscan.jl

Using the example code provided in the documentation, passing three trajectories to 'brainscan_poincaresos`, results in

![image](https://user-images.githubusercontent.com/38593444/135767323-d6ebc447-82d8-4ab0-8b28-536df2933d38.png)

Is there something else that needs to be done?
