### ISSUE TITLE
abm_data_exploration ﻿looking for abm_plot!

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveDynamics.jl#34]
... but it looks like that method has been removed recently.

**Comment by Datseris** [comment]
Huh, does this mean that current `abm_data_exploration` does not work?

**Comment by Libbum** [comment]
Yeah. It's not functional at all. Was going to wait until the name change got merged before attacking it. But if you can see a quick fix with the changes, that'd be great.

**Comment by Datseris** [comment]
I'll have to look at it tonight I guess...

**Comment by Datseris** [comment]
Fixed in version 0.13.1
