### ISSUE TITLE
Limits in Agents DiscreteSpace

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveDynamics.jl#40]
The Maze-Runner has an off-by one issue in its plotting.

Here's the discrepancy:
```julia
heatmap!(ax, walkmap(model); colormap=:grays)

ax.limits
#Observable{GeometryBasics.HyperRectangle{2, Float32}} with 4 listeners. Value:
#GeometryBasics.HyperRectangle{2, Float32}(Float32[0.0, 0.0], Float32[41.0, 41.0])

o, e = modellims(model)
#((0, 0), (42, 42))
```

`modellims` [adds one](https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/9bec50bc87003bac83341cc2b94bc61fb23b9a1a/src/agents/stepping.jl#L81) to the bounding box. I believe we do this so that the markers have some breathing room: (0,0) also will not have any markers in it.

Should we do something about this margin when `static_preplot! !== nothing`, or just get the user to resize limits to their liking?

**Comment by Datseris** [comment]
> I believe we do this so that the markers have some breathing room: (0,0) also will not have any markers in it.

Yes.

> just get the user to resize limits to their liking?

Yes, and they can even do this in the `static_preplot` function. However a quick PR should move these lines https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/9bec50bc87003bac83341cc2b94bc61fb23b9a1a/src/agents/stepping.jl#L67-L71  at the start of the function.
