### ISSUE TITLE
Minor typo on docstring of abm_plot function in /src/agents/plots_videos.jl

### ISSUE THREAD

**Issue by holdon1221** [JuliaDynamics/InteractiveDynamics.jl#46]
I think the below `as(a)` in the **docstring** of abm_plot function in /src/agents/plots_video.jl should be `am(a)` because it sets markers' shape. As a newbie user, it was confusing slightly. 

**Before**
  ```julia
  # ac = "#338c54"
  ac(a) = a.status == :S ? "#2b2b33" : a.status == :I ? "#bf2642" : "#338c54"
  # as = 10
  as(a) = 10*randn() + 1
  # as = :diamond
  as(a) = a.status == :S ? :circle : a.status == :I ? :diamond : :rect
  ```
**After**
  ```julia
  # ac = "#338c54"
  ac(a) = a.status == :S ? "#2b2b33" : a.status == :I ? "#bf2642" : "#338c54"
  # as = 10
  as(a) = 10*randn() + 1
  # am = :diamond
  am(a) = a.status == :S ? :circle : a.status == :I ? :diamond : :rect
  ```

**Comment by Libbum** [comment]
Yep, looks to be the case. You can make a pull request to fix it if you'd like?

**Comment by holdon1221** [comment]
@Libbum I want to but I can't pull my local branch. 
I have the name issue46.
Are there any rules to name remote branches?

**Comment by Libbum** [comment]
Not a rule on branch names, no. But you don't have access to write to this repository directly. Here's what to do:

1. On the top right of this page you can click the fork button. This will give you a copy of the code here you can edit.
2. Clone that repository to your local machine
3. Make the branch, do the edit as you have now, then push it.
4. Come back to the [main page](https://github.com/JuliaDynamics/InteractiveDynamics.jl) of this repository, you should see a banner to create a pull request.

**Comment by holdon1221** [comment]
@Libbum Wow thanks for your kind and detail answers.

**Comment by Libbum** [comment]
Always happy to help out people new to github and to JuliaDynamics! Feel free to ask us anything if you run into trouble.
