### ISSUE TITLE
Makie 0.13 Upgrade

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveDynamics.jl#50]
https://discourse.julialang.org/t/ann-makie-v-0-13/61522

TODOs:
- [ ] Replace `AbstractPlotting` with `Makie`
- [ ] Update heatmap and agent plotting routines to make sure the new `heatmap` doesn't give us any off-by-one issues

**Comment by ndgnuh** [comment]
Is it because of this that I get the `LoadError: No backend available (GLMakie, CairoMakie, WGLMakie)!` error even when I installed CairoMakie and properly built it?

**Comment by Datseris** [comment]
probably :P I guess this is high priority, will get to it this weekend if we don't get a lovely PR from a lovely contributor

**Comment by Datseris** [comment]
Should be a simple search and replace `AbstractPlotting` -> `Makie` and just update Project.toml

**Comment by ndgnuh** [comment]
It is really just replace the name and nothing else? (yes I read the link) Sounds very magical to me.

If so I can do a quick sed to replace everything

**Comment by Libbum** [comment]
Yep, it's a breaking change, but very minimal in the grand scheme of things. There may be some edge cases for Agents.jl heatmaps, but that can be dealt with after the upgrade in a separate PR.

**Comment by ndgnuh** [comment]
Cool, I opened a pr #51
