### ISSUE TITLE
Agents plots with `Scheduler.randomly` are not reproduceable

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveDynamics.jl#54]
JuliaDynamics/Agents.jl#502 identified a reproducibility issue in the data collection system, now that that is fixed there is also one in plotting.

If `Scheduler.randomly` is used to plot things, we alter the internal state of the model and therefore mutate the models expected output too.

Problem is [this call to the scheduler](https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/e000d0dc806735c27ace6ae35f8f0455608d0431/src/agents/stepping.jl#L70).

**Comment by Datseris** [comment]
If the user doesn't want to trigger randon number generation calling when using this function, they have to use a different scheduler. I do not see a problem.

**Comment by Libbum** [comment]
True. 

I think maybe extending this docstring with a note about mutability:

> `scheduler = model.scheduler`: decides the plotting order of agents (which matters only if there is overlap).

to

> `scheduler = model.scheduler`: decides the plotting order of agents (which matters only if there is overlap). **Note:** avoid using the `randomly` scheduler if model reproducibility from a specific set of seeds is important.

**Comment by Datseris** [comment]
Sure (but also, this should be quite obvious I feel)

**Comment by Datseris** [comment]
Actually, I'm not sure this would improve the documentation. Stating the obvious in every opportunity would lead to a 3000 word docstring.

**Comment by Libbum** [comment]
OK. I'll close this, merge the Agents fix and we can refer to these issues if it ever crops up again.
