### ISSUE TITLE
Rethink axis limits for Agents plotting

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveDynamics.jl#59]
https://juliadynamics.github.io/Agents.jl/stable/examples/predator_prey_fast/

Offsets are not considered at all currently, so plots end up looking cut off, e.g.:

![image](https://user-images.githubusercontent.com/3059508/124245567-62ebf780-db20-11eb-91e2-67a17447a9a6.png)

**Comment by Datseris** [comment]
I've fixed that on new release. The key was putting 0.5 as start and `end + 0.5` as end.
