### ISSUE TITLE
Reset the whole view of interactive app

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/InteractiveDynamics.jl#74]
While exploring my ABMs, I often find myself updating parameters and resetting the model over and over again. Because of this, I'd like an ability to reset the whole view of the interactive app, i.e. having completely "blank" plots and a fresh view of the space and so on.

This could be done either via a new `clear` button or by extending the functionality of the existing `reset` button. Currently `reset` resets the underlying model to its initial state and draws a red vertical line in the plots after which the new series are drawn. Was this just a temporary workaround or was it a deliberate design decision to never completely clear the plots? Which option would you prefer - a new button or changing how the existing one works? Would love to hear your thoughts on this.

**Comment by Libbum** [comment]
Pretty sure George was thinking that the restart line shows a discontinuation in an effectively infinite exploration. What that doesn't cover in my view, are models that have a clear temporal start and end. I think this is what you're hitting here as well.

I like the red lines for continuous resets, and I think your additional behaviour is welcomed. Best of both worlds makes adding a new button the `clear` winner.

**Comment by Datseris** [comment]
yeah adding a new `clear` button is the way to go and thankfully quite simple given the current code. just copy the reset button and make it also make the plotted curves to be ` = Point2f0[]`.
